# Wrangler configuration for Cloudflare Pages deployment
name = "derpcat-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[env.production]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (these should be set in Cloudflare dashboard)
[env.production.vars]
# Add your environment variables here or set them in Cloudflare dashboard
# BANDSINTOWN_ARTIST_NAME = "your-artist-name"
# BANDSINTOWN_APP_ID = "your-app-id"
# PATREON_CLIENT_ID = "your-patreon-client-id"
# PATREON_CLIENT_SECRET = "your-patreon-client-secret"

[env.preview]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build:cloudflare"
cwd = "."

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Function configuration for Edge Runtime
[[env.production.services]]
binding = "ASSETS"
service = "cloudflare-pages-assets"

# Custom headers and redirects
[env.production.routes]
"/*" = "index.html"

# Development configuration
[env.development]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
